apiVersion: v1
kind: Template
metadata:
  name: logcollector
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: collector-service-account
#
# Deployment of fluentd log collector
#
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: fluentd
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: fluentd
    template:
      metadata:
        labels:
          app: fluentd
      spec:
        serviceAccountName: collector-service-account
        containers:
        - image: ${fluentd_image}
          securityContext:
            runAsUser: 0
            privileged: true
            allowPrivilegeEscalation: true
          imagePullPolicy: Always
          name: fluentd
          command: ["/bin/bash"]
          args:
            - -c
            - >
              rm -r /var/log/containers/fluentd.stresslog;
              rm /var/log/containers/stress.log;
              echo "Installing loki plugin";
              yum update -y;
              yum install -y gcc make autoconf;
              yum install -y redhat-rpm-config;
              echo "Apply custom pre-commands";
              cp /fluentd-pre-sh/fluentd_pre.sh fluentd_pre.sh;
              chmod +x fluentd_pre.sh;
              ./fluentd_pre.sh;
              echo "Starting fluentd";
              /usr/local/bin/fluentd -c /etc/fluentd/fluentd.conf;
              while true; do
                echo ".";
                sleep 60;
              done;
          volumeMounts:
          - name: varlog
            mountPath: /var/log
          - name: config-path
            mountPath: /etc/fluentd
          - name: fluentd-pre-sh
            mountPath: /fluentd-pre-sh
        restartPolicy: Always
        volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: config-path
          configMap:
            name: fluentd-config        
        - name: fluentd-pre-sh
          configMap:
            name: fluentd-pre-sh

  #
# Service for fluentd forward port
#
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: fluentd
    name: fluentd-forward
  spec:
    ports:
      - name: forward
        port: 24224
        protocol: TCP
        targetPort: 24224
    selector:
      app: fluentd
    sessionAffinity: None
    type: ClusterIP
parameters:
  - name: fluentd_image
